name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build -t my-app .
          docker tag my-app my-repo/my-app:${{ github.sha }}
          
      - name: Run Trivy scan (Critical/HIGH only)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app'
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          security-checks: 'vuln'
          
      - name: Optional: Medium severity report
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app'
          format: 'table'
          severity: 'MEDIUM'
          exit-code: '0'
          ignore-unfixed: true
          
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
